### ISSUE TITLE
Safely comparing HMAC

### ISSUE THREAD

**Issue by lukeclifton** [ANSUGroup/shopify#1]
https://github.com/ANSUGroup/shopify/blob/27611db2ed5784df7db90246626c158d7d2ba12a/packages/verify-hmac-request/src/index.ts#L38

Do you need to use something like: https://www.npmjs.com/package/safe-compare here to prevent against a potential Node.js timing attack here?

**Comment by pierreneter** [comment]
thanks, @lukeclifton I will add it now

**Comment by pierreneter** [comment]
thanks @lukeclifton, resolved that and create a release with tag: [v0.1.4](https://github.com/ANSUGroup/shopify/releases/tag/v0.1.4)
